name: evc
description: Flutter app for Echo value calculations with resonator browsing and scoring
publish_to: "none"
version: 1.6.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  html: ^0.15.6
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  file_picker: ^10.3.3
  window_manager: ^0.5.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/attribute_icons/
    - assets/resonator_icons/
    - assets/resonator_portraits/
    - assets/stat_icons/
    - assets/weapon_icons/
