name: evc
description: Flutter app for Echo value calculations with resonator browsing and scoring
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  html: ^0.15.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  file_picker: ^10.3.3
  window_manager: ^0.5.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/portraits/
    - assets/attributes/
    - assets/weapons/
    - assets/stats/
