import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:evc/core/result.dart';
import 'package:evc/core/providers/notification_provider.dart';
import 'package:evc/core/providers/service_providers.dart';
import 'package:evc/core/providers/shared_preferences_provider.dart';
import 'package:evc/core/router.dart';
import 'package:evc/domain/enums/stat.dart';
import 'package:evc/infrastructure/services/resonator_service_impl.dart';
import 'package:evc/infrastructure/services/storage_service_impl.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Pre-initialize SharedPreferences
  final prefs = await SharedPreferences.getInstance();

  // Load resonator definitions
  final resonatorSvc = ResonatorServiceImpl();
  await resonatorSvc.load();

  final resonators = resonatorSvc.resonators;
  final storageSvc = StorageServiceImpl();
  storageSvc.setResonators(resonators);

  // Migrate saved echo sets whose resonator IDs changed in this release.
  _migrateEchoSets(storageSvc);

  runApp(
    ProviderScope(
      overrides: [
        sharedPreferencesProvider.overrideWithValue(prefs),
        resonatorServiceProvider.overrideWithValue(resonatorSvc),
        storageServiceProvider.overrideWithValue(storageSvc),
      ],
      child: const EchoValueCalcApp(),
    ),
  );
}

/// Migrate saved echo sets when resonator IDs change between releases.
///
/// The migration map is generated by the sync script and bundled as an asset.
/// On each launch we load it and rename any matching keys in echo_sets.json.
/// This is safe to call on every startup — it's a no-op when no migrations exist
/// or when the user has no saved data for the affected IDs.
Future<void> _migrateEchoSets(StorageServiceImpl storage) async {
  try {
    final json = await rootBundle
        .loadString('assets/data/resonator_id_migrations.json');
    final map = jsonDecode(json) as Map<String, dynamic>;
    final migrations = Map<String, String>.from(map);

    final result = await storage.migrateEchoSets(migrations);
    switch (result) {
      case Ok(value: final count) when count > 0:
        debugPrint('[migrate] Renamed $count saved echo set(s) '
            'to match updated resonator IDs.');
      case Ok():
        break; // nothing to migrate
      case Err(message: final msg):
        debugPrint('[migrate] Migration skipped: $msg');
    }
  } catch (_) {
    // Asset not found or malformed — nothing to migrate.
  }
}

class EchoValueCalcApp extends ConsumerStatefulWidget {
  const EchoValueCalcApp({super.key});

  @override
  ConsumerState<EchoValueCalcApp> createState() => _EchoValueCalcAppState();
}

class _EchoValueCalcAppState extends ConsumerState<EchoValueCalcApp> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      if (!mounted) return;

      // Precache all images in parallel
      final futures = <Future>[];

      for (final stat in Stat.all) {
        futures.add(precacheImage(AssetImage(stat.assetPath), context));
      }

      final resonators = ref.read(resonatorServiceProvider).resonators;
      for (final resonator in resonators) {
        futures.add(precacheImage(AssetImage(resonator.iconAsset), context));
      }

      await Future.wait(futures);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Echo Value Calculator GUI',
      // Dark theme only — no theme switching
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.indigo,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      darkTheme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.indigo,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      themeMode: ThemeMode.dark,
      routerConfig: router,
      builder: (context, child) => ToastLayer(child: child!),
    );
  }
}
